# Generated by Django 4.2 on 2023-04-25 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reduce', '0003_remove_urlredirect_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlredirect',
            name='shortened',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
    ]
